"total_fake_nodes": 20
"fake":
    "interface": "eth0",
    "router_id": 99,
    "ip": "192.0.0.1",
    "mac": "aa:bb.cc:dd.ee:01"
"real":
    "interface": "eth1",
    "router_id": 1,
    "ip": "192.0.0.2",
    "mac": "aa:bb:cc:dd:ee:02"